### ISSUE TITLE
Runway could not find [usertypes] resource

### ISSUE THREAD

**Issue by HazemMohamed252** [doublethreedigital/runway#134] opened 2022-04-04 22:05 UTC
### What's the issue you're running into?

After creating resource and it's blueprint then i deleted it from runway config suddenly this error appears : 
Runway could not find [usertypes]. Please ensure its configured properly and you're using the correct handle. (View: \vendor\statamic\cms\resources\views\partials\scripts.blade.php)

I am trying to delete it because i don not want it anymore. Please help

### Steps to reproduce

1. Create model as resource
2. Add it to runway config
3. Create related blueprint
4. Remove it from runway config 

Error occured

### Environment

Statamic 3.2.37 Pro
Laravel 8.83.4
PHP 7.4.11
doublethreedigital/runway 2.3.0
jacksleight/statamic-lazy-logo 0.3.3
vannut/statamic-weather-addon 1.0.1

**Comment by duncanmcclean** [comment] 2022-04-05 06:12
What does your Runway config look like?

**Comment by HazemMohamed252** [comment] 2022-04-05 08:44
@duncanmcclean 
\App\Models\UserTypes::class => [
            'name' => 'User Types',
            'blueprint' => 'collections/pages/usertypes'
        ],

**Comment by duncanmcclean** [comment] 2022-04-05 08:51
Let me get this straight... you deleted the model and blueprint but you still have it in your Runway config? Am I misunderstanding what the issue is?

**Comment by HazemMohamed252** [comment] 2022-04-05 08:58
A deleted the model and the blueprint yaml file and also remove the above line from Runway config. By the way i did these steps for multi models and blueprints and once remove from Runway config file it works fine and disappeared from the CP , but this is the only model that have the issue

**Comment by duncanmcclean** [comment] 2022-04-05 09:01
Do a project-wide find for `usertypes`. You'll probably find a reference somewhere which will be causing the issue.

**Comment by HazemMohamed252** [comment] 2022-04-05 09:04
I can  not explain but as i said i just create the blueprint and the resource as Runway documentation and follow the docs and as i said when i remove any model and remove it from the runway config everything goes right BUT this is the ONLY model that cause issue, and no other reference for it in the project

**Comment by duncanmcclean** [comment] 2022-04-05 09:21
Have you tried clearing the cache? There must be a reference to it somewhere or you wouldn't be getting the error.

**Comment by HazemMohamed252** [comment] 2022-04-05 09:24
I did the all, optimize , clear route and cache, and also composer dump-autoload, the model is UserTypes and i was have another model cal UserType that was just for test but i deleted the two.

**Comment by duncanmcclean** [comment] 2022-04-05 09:34
What did you search for? `usertypes` (lowercase, one word) or `UserTypes`?

**Comment by HazemMohamed252** [comment] 2022-04-05 09:37
UserTypes is the model name but the blueprint file is : usertypes.yaml

**Comment by duncanmcclean** [comment] 2022-04-05 09:40
Yes, `usertypes` will be the handle of the model in Runway. Any references to the Runway resource will be to `usertypes`. That's what you have to do a project-wide find of.

**Comment by HazemMohamed252** [comment] 2022-04-05 09:44
Sorry but i need to explain more, For example i have i model is : Product and a blueprint is : product and everything right and when i deleted the Product model and remove it's config from Runway config file it works fine and disappeared, why the UserTypes model that cause the issue

**Comment by duncanmcclean** [comment] 2022-04-05 15:46
Hmm, not quite sure how else to help. The only reason that would be happening is due to a reference somewhere (in a config, in another blueprint, in custom code). 

I can take a look at your codebase when I have some free time in case there's anything I can't see that you're missing? However, there's not much more I can do. I don't think it's a bug in Runway so I'm going to close this issue.

**Closed by duncanmcclean** 2022-04-05 15:46 UTC
Labels: needs more info
